### ISSUE TITLE
打包不显示UI

### ISSUE THREAD

**Issue by BadZhang** [redcool/PowerURPPipeline_unity2021#1]
编辑器 GameView 视图 正常  关闭 UI Mask 后  SceneView视图 不显示UI.

<img width="526" alt="image" src="https://user-images.githubusercontent.com/10047133/176842461-097574bf-76dc-4c59-997e-3b2b4f648485.png">

 测试了 PC 包 和 Android 包 均不显示UI.
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/10047133/176839839-7fc3ad09-9388-4946-a598-c6e20a3f1a96.png">

只有勾选了 UI Mask  出包 才会显示UI 但是是重复的两层.

**Comment by BadZhang** [comment]
URP 12 => RenderTargetBufferSystem

**Comment by redcool** [comment]
hi,感谢反馈.
当时的开发版本是 unity 2021.2.14,&nbsp;
这个版本是正常,包括 urp, gamma ui



之后的 unity,应该是不能用2021.2.14的urp了.
有空时,我再整合一个 unity2021.3.x吧.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bad ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [redcool/PowerURPPipeline_unity2021] 打包不显示UI (Issue #1)





 
URP 12 =&gt; RenderTargetBufferSystem
 
&mdash;

**Comment by redcool** [comment]
hi,感谢反馈.
当时的开发版本是 unity 2021.2.14, 
这个版本是正常,包括 urp, gamma ui



之后的 unity,应该是不能用2021.2.14的urp了.


https://github.com/redcool/PowerURPPipeline_unity2021.git
这个库里,提了了 12.1.7,是对应unity 2021.3.4的urp,
可用使用这个测试一下.


我发布的pc包,是正常工作的.




------------------ 原始邮件 ------------------
发件人: "Bad ***@***.***&gt;; 
发送时间: 2022年7月11日(星期一) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [redcool/PowerURPPipeline_unity2021] 打包不显示UI (Issue #1)





 
URP 12 =&gt; RenderTargetBufferSystem

**Comment by redcool** [comment]
bug fixed.
